# Generated by Django 5.1.2 on 2024-10-31 05:56

import django_jalali.db.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('site', 'درخواست سایت'), ('work', 'راه اندازی کسب و کار'), ('couns', 'مشاوره')], default='site', max_length=5)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cours_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', django_jalali.db.models.jDateField(auto_now=True)),
                ('profile_img', models.ImageField(default='comments/b-1.png', upload_to='comments')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', django_jalali.db.models.jDateField(auto_now=True)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=1, size=[348, 232], upload_to='courses')),
                ('basin', models.CharField(choices=[('دوره تحلیلی داده', 'دوره تحلیلی داده'), ('دوره پیشرفته وب', 'دوره پیشرفته وب'), ('دوره مقدماتی برنامه نویسی', 'دوره مقدماتی برنامه نویسی')], default='دوره تحلیلی داده', max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('type_model', models.CharField(choices=[('گرافیک', 'گرافیک '), ('طراحی سایت', 'طراحی سایت'), ('زبان برنامه نویسی', 'زبان برنامه نویسی'), ('هک و امنیت', 'هک و امنیت')], default='', max_length=25)),
                ('decription', models.TextField(default='')),
                ('hourse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=1, size=[368, 368], upload_to='teachers')),
                ('resume', models.FileField(default='', upload_to='resume')),
                ('Expertise', models.CharField(choices=[('مدرس برتر ریاضی و فیزیک"', 'مدرس برتر ریاضی و فیزیک'), ('مدرس برتر شیمی', 'مدرس برتر شیمی'), ('دکترای آموزش زبان انگلیسی', 'دکترای آموزش زبان انگلیسی'), ('مدرس برتر پایتون/جاوا اسکریپت', 'مدرس برتر پایتون/جاوا اسکریپت'), ('مؤلف و مدرس شیمی کنکور', 'مؤلف و مدرس شیمی کنکور')], default='مدرس برتر ریاضی و فیزیک', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('discribe', models.TextField(default='')),
                ('skill1', models.CharField(blank=True, default='', max_length=150)),
                ('skill2', models.CharField(blank=True, default='', max_length=150)),
                ('skill3', models.CharField(blank=True, default='', max_length=150)),
                ('skill4', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
    ]
