# Generated by Django 5.1.2 on 2024-10-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_teachers_skill1_alter_teachers_skill2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='skill4',
        ),
        migrations.AddField(
            model_name='teachers',
            name='level1',
            field=models.CharField(blank=True, choices=[('low', 'مبتدی'), ('beginner', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'حرفه\u200cای'), ('master', 'استاد')], max_length=150),
        ),
        migrations.AddField(
            model_name='teachers',
            name='level2',
            field=models.CharField(blank=True, choices=[('low', 'مبتدی'), ('beginner', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'حرفه\u200cای'), ('master', 'استاد')], max_length=150),
        ),
    ]
